### ISSUE TITLE
Feature: add option to choose initial DOM container of the popper-content when using "inline popper"

### ISSUE THREAD

**Issue by iceteabottle** [tonysamperi/ngx-popperjs#20] opened 2022-02-28 11:09 UTC
**Describe the bug**
The NgxPopperjsContentComponent increases gaps in grid or flex layout because it will be initially added as sibling of the trigger component wich are flex children in my case. 

**To Reproduce**
1. Add buttons in a grid or flex layout (with a defined gap)
2. Apply some text via the popper directive to the buttons
3. Inspect the grid or flex
4. You'll see gaps of the invisible `<popper-content/>` elements

**Expected behavior**
The popper directive should not have any impact on a grid or flex layout.

**Screenshots**
Bug:
![bug](https://user-images.githubusercontent.com/13260952/155972984-bf7af46c-6331-4607-ad65-aeb535f9cb88.png)
Button 2 and 3 have a tooltip.

Expected:
![expected](https://user-images.githubusercontent.com/13260952/155972989-89772f34-b44d-457e-a60d-e2ef534aaf76.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.1 (doesn't matter)
 - Browser: Chrome 98 (doesn't matter)
 - Version: 12.2.1

**Additional context**
My workaround currently:
````
body {
  > * popper-content {
    display: none;
  }
}
````

I guess the main problem is, that the popper component get's only moved away (appended at body in my case) on `show()`...

**Comment by tonysamperi** [comment] 2022-02-28 11:13
I guess the main problem is...your code :)

I used the plugin in several flex projects with @angular/flex and it works just fine.
I think you should provide a blitz.
Closing this for now.

Also, on a sidenote you can decide where the popper gets appended...see the docs, I don't remember the parameter name.

**Comment by iceteabottle** [comment] 2022-03-01 05:42
Thanks again for your fast response.

> Also, on a sidenote you can decide where the popper gets appended...

Yes but the popper will be moved away only on `show()`. Initially it lays beneath the trigger.

> I guess the main problem is...your code :)

Well... no not really^^ I will provide an example soon.

**Comment by iceteabottle** [comment] 2022-03-04 10:12
Et voilá: https://stackblitz.com/edit/angular-ivy-u2bzvb?file=src/app/app.component.html

And of course I could wrap each button with a div to solve it. But that would result in superfluous markup that all my colleagues would to remember every time they implement a tooltip. That's not a good idea. Currently my css workaround works. But I think the problem should be easy to solve for you :)

**Comment by tonysamperi** [comment] 2022-03-04 11:17
I'm sorry pal, but the issue is on your end. You're using flex gap knowing that there's an extra element in the same flex box.
The solution here is quite obvious, if you don't want to wrap with an extra div, you don't use inline poppers...
You do something like this instead:

```
<div class="button-poppers">
  <popper-content #btn1>This is a tooltip</popper-content>
  <popper-content #btn3>This is a tooltip</popper-content>
</div>
<div class="buttons">
  <button>Button 1</button>
  <button [popper]="btn1" [popperAppendTo]="'body'">
    Button 2
  </button>
  <button [popper]="btn3" [popperAppendTo]="'body'">
    Button 3
  </button>
  <button>Button 4</button>
</div>
```

And it works like charm!
I could actually implement an extra parameter to choose where the popper-content is appended upon creation, but it would require a lot of work since I wouldn't be able to use the viewContainerRef of the hosting element...
It's quite a long development, which honestly doesn't seem so necessary...
We can do like the Angular team...if this post gets 20 thumbs (by 30 days from this post, so on April 3rd) I'll do the implementation!

**Comment by iceteabottle** [comment] 2022-03-04 11:38
> You're using flex gap knowing that there's an extra element in the same flex box.

After investigate this, I know it now. But that's totally unexpected...

**Comment by tonysamperi** [comment] 2022-03-04 12:12
> > You're using flex gap knowing that there's an extra element in the same flex box.
> 
> After investigate this, I know it now. But that's totally unexpected...

The most important thing is that I was right!
The problem is...your code! 😂

**Comment by tonysamperi** [comment] 2022-04-13 19:13
Closing this, we'll reevaluate in the future this topic.

Cheers to everyone!

**Closed as completed by tonysamperi** 2022-04-13 19:13 UTC
Labels: enhancement, under consideration
