### ISSUE TITLE
BUG: chrome fix introduces breaking changes for certain custom styles

### ISSUE THREAD

**Issue by bersling** [tonysamperi/ngx-popperjs#56] opened 2023-08-03 14:28 UTC
**Describe the bug**

The chrome fix introduces breaking changes for certain custom styles, especially for overrides to the `border`.

**To Reproduce**

v15.2.1: https://stackblitz.com/edit/stackblitz-starters-zayapw?file=src%2Fmain.ts
v15.2.2: https://stackblitz.com/edit/stackblitz-starters-ntdnfh?file=src%2Fmain.ts

The stackblitzes are identical except for the ngx-popperjs version, yet they result in different UIs.

**Expected behavior**
A minor version update shouldn't change anything, as long as legitimate properties are used such as `[popperStyles]`. Also, I think it's now not possible anymore to change the border without introducing this behavior that the border doesn't go away?

**Screenshots**

v15.2.1
![Screenshot 2023-08-03 at 16 26 37](https://github.com/tonysamperi/ngx-popperjs/assets/10352805/ee487b43-dde1-46cc-ac3e-58417a805d41)

v15.2.2
![Screenshot 2023-08-03 at 16 26 53](https://github.com/tonysamperi/ngx-popperjs/assets/10352805/5b33fd16-51da-4483-8e0e-144b120cabc5)

**Versions**
 - ngx-popperjs version: 15.2.2, 16.0.2 (all versions with the chrome fix)

(Also, the issue template for `Version` has a bug ;))

**Comment by tonysamperi** [comment] 2023-08-03 14:35
And that's why you don't use inline styling. Sorry man but it's a bad implementation on your side.
You should use CSS to do such styling.
The huge bug on the latest Chrome versions has the priority. And btw I took care of not editing the appearance...
But of course if your style overrides the theme CSS is your problem!

**Comment by tonysamperi** [comment] 2023-08-03 14:38
I could add `!important` on the hide stylings though...

**Comment by bersling** [comment] 2023-08-03 14:54
What's the suggested way to override the default stylings? `popperApplyClass`? I can of course migrate to that then. But I'd suggest you deprecate `[popperStyles]` if it's not supported, I wouldn't say it's on me if this library is offering support for that.

**Comment by bersling** [comment] 2023-08-03 14:56
I thought of the `!important` too, but (a) users could also have `!important` so then that would win anyways and it's only half a fix and (b) you'd need to know all classes users possibly apply. I don't see an easy way how you could properly fix it?

**Comment by tonysamperi** [comment] 2023-08-03 15:00
Well the best way to override the default stylings is using SCSS and create your own theme.
The other way could be `disableDefaultStyling`, but honestly I don't remember how it works exactly.
Anyway I'm adding the `! important` right away, so you won't need to change anything.

About users having `! important`. That's another thing you don't do. You never use `! important` unless you really have no choice. The "rule" is creating more specific CSS selectors.
So for now I'll use the important.
And I will do a completely new implementation in v17 using the new floating UI (which hopefully works better with this Chrome update). Damn Google guys!

By the way I tried several fixes, but they must have changed something about how DOM is updated, because I always got the updated css class in the DOM 50ms after the popper checks for the position where executed.
At some point I tried using a timeout of 50 milliseconds. It worked but it was horrible as the popover was shown for a few ms in one place and moved immediately. But of course if you have a slower PC the risk is really seeing that. 
Too horrible for me :D

**Comment by bersling** [comment] 2023-08-03 15:06
Thanks for the explanation, I'll try to update to the custom theme then!

**Comment by tonysamperi** [comment] 2023-08-03 16:42
Fixed in v 16.0.4 (equivalent v15 and v14 coming in a few minutes)

**Closed as completed by tonysamperi** 2023-08-03 16:42 UTC
Labels: bug

**Comment by bersling** [comment] 2023-08-03 16:57
The custom theme is a bit limited, it only allows for the following properties if I'm not mistaken:

```
@mixin ngx-popperjs-theme($background, $text, $max-width: $default-max-width, $z-index: $default-z-index) {
```

Specifically `width` and `padding` are important for our use case.

I migrated to the custom theme for the supported properties and for the other ones I used `popperApplyClass`. That should cause less headaches, since it has low prio (popper-special-style-feedback in the screenshot).

![Screenshot 2023-08-03 at 18 44 27](https://github.com/tonysamperi/ngx-popperjs/assets/10352805/b9256e16-6c63-465c-8b7d-a12c8f0cc4bc)

It can't be used to override any of your styles since in hidden as well as in non hidden mode it comes after your selectors. So for example overriding the box shadow isn't possible like this. I dropped it since it wasn't as important to me, but if it was important, I'd have to use the custom styles or otherwise use the dreaded `!important` in the css class.

**Comment by tonysamperi** [comment] 2023-08-03 17:01
@bersling I said to create a custom theme, not to use the helper mixin!

That said, yes. Popper apply class should be more effective if you need to override something!

**Comment by bersling** [comment] 2023-08-04 06:56
I tried to follow the readme on this, which reads:

```
Optionally you can include in your styles.css / styles.css one of the prebuilt themes:

    @import node_modules/ngx-popperjs/css/theme-dark.css

    @import node_modules/css/theme-white.css

    @use ngx-popperjs/scss/theme as popperBaseTheme

    @use ngx-popperjs/scss/theme-dark as popperDarkTheme

    @use ngx-popperjs/scss/theme-white popperWhiteTheme

or easily create your own theme using the @mixin:

@use "ngx-popperjs/scss/theme" as popperBaseTheme;

body {
    @include popperjs.ngx-popperjs-theme($background-color, $text-color, $max-width, $z-index);
}
```

So I thought including this mixin is what you meant. If it's not this I'm not sure what you mean by custom theme, is there any other documentation on this, or do you have an example?

**Comment by tonysamperi** [comment] 2023-08-04 07:28
> I tried to follow the readme on this, which reads:
> 
> ```
> Optionally you can include in your styles.css / styles.css one of the prebuilt themes:
> 
>     @import node_modules/ngx-popperjs/css/theme-dark.css
> 
>     @import node_modules/css/theme-white.css
> 
>     @use ngx-popperjs/scss/theme as popperBaseTheme
> 
>     @use ngx-popperjs/scss/theme-dark as popperDarkTheme
> 
>     @use ngx-popperjs/scss/theme-white popperWhiteTheme
> 
> or easily create your own theme using the @mixin:
> 
> @use "ngx-popperjs/scss/theme" as popperBaseTheme;
> 
> body {
>     @include popperjs.ngx-popperjs-theme($background-color, $text-color, $max-width, $z-index);
> }
> ```
> 
> So I thought including this mixin is what you meant. If it's not this I'm not sure what you mean by custom theme, is there any other documentation on this, or do you have an example?

With a bit of fantasy you take the SCSS source and write your own theme!
Sorry but I don't have any examples to show...

**Comment by bersling** [comment] 2023-08-04 07:48
So you mean in my scss I should do something like:

```
::ng-deep {
   div.ngxp__container {
     background: $background;
     color: $text;
     border: 0;
     max-width: $max-width;
     box-shadow: 0 3px 5px -1px rgba(0, 0, 0, 0.2), 0 5px 8px 0 rgba(0, 0, 0, 0.14), 0 1px 14px 0 rgba(0, 0, 0, 0.12);
     z-index: $z-index;
     // other stuff i want to do
 
     > .ngxp__arrow {
       &:before {
         background-color: $background;
       }
     }
   } 
}
```

?

Then I'd have to rely on internals of your implementation, e.g. that you named your class `ngxp__arrow` and my styling would break if you'd change something about that?

**Comment by tonysamperi** [comment] 2023-08-04 07:52
> So you mean in my scss I should do something like:
> 
> ```
> ::ng-deep {
>    div.ngxp__container {
>      background: $background;
>      color: $text;
>      border: 0;
>      max-width: $max-width;
>      box-shadow: 0 3px 5px -1px rgba(0, 0, 0, 0.2), 0 5px 8px 0 rgba(0, 0, 0, 0.14), 0 1px 14px 0 rgba(0, 0, 0, 0.12);
>      z-index: $z-index;
>      // other stuff i want to do
>  
>      > .ngxp__arrow {
>        &:before {
>          background-color: $background;
>        }
>      }
>    } 
> }
> ```
> 
> ?
> 
> Then I'd have to rely on internals of your implementation, e.g. that you named your class `ngxp__arrow` and my styling would break if you'd change something about that?

No, I wouldn't put that style in some component. You should have it in the styles.scss.
Anyway those classes cannot change until v17.
You can use those without worrying about changes.

Cheers

**Comment by andreivarlamov** [comment] 2023-09-01 16:35
I got this bug after the upgrade from 14.1.6 to 14.1.8, is it related to the bug you fixed?

https://github.com/tonysamperi/ngx-popperjs/assets/108550569/1fd492ef-58f6-4c91-bd52-63b309996d2a

**Comment by tonysamperi** [comment] 2023-09-03 09:26
> I got this bug after the upgrade from 14.1.6 to 14.1.8, is it related to the bug you fixed?
> 
>  2023-09-01_11-25-37.mp4

Hi @andreivarlamov 

could be. It's weird because if you saw the fix, I ended up delaying the popper instance creation...
Maybe it has something to do with the "hover" trigger.
I'll try this in my demo page and tell you if I have the same behaviour.

**EDIT**

@andreivarlamov I confirm you that I don't have such a behaviour when reproducing your scenario.
I just have that issue if I enter and exit wildly from the target.
I'm checking if something can be done to improve.

**Comment by andreivarlamov** [comment] 2024-03-28 20:09
Hi @tonysamperi, thank you for your help. I finally reproduced that bug, it's because of popperDisableStyle=true option. Still exists in 15.2.4.

**Comment by tonysamperi** [comment] 2024-03-28 21:06
@andreivarlamov can you create a blitz?

**Comment by andreivarlamov** [comment] 2024-03-28 21:11
https://stackblitz.com/edit/stackblitz-starters-nefrn2?file=src%2Fmypopper%2Fmypopper.component.html

And you're right, if the trigger is Hover and you enter-exit from the target quickly it works buggy even with enabled default styles. Version 15.2.1 works much better.

**Comment by tonysamperi** [comment] 2024-03-29 10:11
Hey @andreivarlamov 

thanks! Now I was able to understand what's going on!

Honestly I never understood why this problem was born.
In fact I've actually discovered that the problem is always there, but is just masked even if you don't remove styles.
The mask is the animation!
If you just use the `popperDisableAnimation` attribute, you'll see the same problem.

I'm pushing a fix right now.

I was able to fix by separating the change on "display" and "opacity".

**Comment by tonysamperi** [comment] 2024-03-29 10:38
@andreivarlamov nope, I spoke too soon. It doesn't work and now I broke v16.
I'm sorry pal, but there's really no solution with popper.
I suggest you move to ngx-float-ui, since I released v15 yesterday.
That doesn't have the issue.

Damn now I have to revert v16

But if you want to give it a try in your blitz => v16.0.8 (now deprecated)

https://stackblitz.com/edit/stackblitz-starters-jnggcc?file=package.json,src%2Fmypopper%2Fmypopper.component.html
